list_bodyparts = {...
    'Nose'...
    ;'Neck'...
    ;' Rt_Shoulder'...
    ;' Lt_Shoulder'...
    ;' Rt_Elbow'...
    ;' Lt_Elbow'...
    ;' Rt_Hand'...
    ;' Lt_Hand'...
    ;' Back'...
    ;' Rt_Hip'...
    ;' Lt_Hip'...
    ;' Rt_Knee'...
    ;' Lt_Knee'...
    ;' Rt_Foot'...
    ;' Lt_Foot'...
    ;' Rt_Toe'...
    ;' Lt_Toe'};